//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaoticRNG01.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaoticRNG01.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:   r =4.0 \\\\ iterations = 2000,  transcient = 1000..
        /// </summary>
        public static string ChaoticRandomNumberGeneratorContent {
            get {
                return ResourceManager.GetString("ChaoticRandomNumberGeneratorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic Random Number Generator.
        /// </summary>
        public static string ChaoticRandomNumberGeneratorTitle {
            get {
                return ResourceManager.GetString("ChaoticRandomNumberGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get JSON.
        /// </summary>
        public static string GJSON {
            get {
                return ResourceManager.GetString("GJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From pseudo random numbers to real random numbers..
        /// </summary>
        public static string lead {
            get {
                return ResourceManager.GetString("lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic Map.
        /// </summary>
        public static string LogisticMap {
            get {
                return ResourceManager.GetString("LogisticMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This WebApp uses a Pseudo-Random number generator using the .Net class called.
        /// </summary>
        public static string LogisticMapTheoryContent {
            get {
                return ResourceManager.GetString("LogisticMapTheoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to introduced in .Net 4.5 as pesudo-random number generator that meets statistical requiremets for randomness.
        /// </summary>
        public static string LogisticMapTheoryContent2 {
            get {
                return ResourceManager.GetString("LogisticMapTheoryContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now using this generator and the.
        /// </summary>
        public static string LogisticMapTheoryContent3 {
            get {
                return ResourceManager.GetString("LogisticMapTheoryContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equation with the parameter r=4 to be sure to be in the chaotic response and iterate the equation three thousand times..
        /// </summary>
        public static string LogisticMapTheoryContent4 {
            get {
                return ResourceManager.GetString("LogisticMapTheoryContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic Map Theory.
        /// </summary>
        public static string LogisticMapTheoryTitle {
            get {
                return ResourceManager.GetString("LogisticMapTheoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Api Json random numbers.
        /// </summary>
        public static string MultipleGeneratorTitle {
            get {
                return ResourceManager.GetString("MultipleGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Generator Number.
        /// </summary>
        public static string SingleGeneratorTitle {
            get {
                return ResourceManager.GetString("SingleGeneratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std Deviation.
        /// </summary>
        public static string StdDes {
            get {
                return ResourceManager.GetString("StdDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaotic Random Generator Number.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
    }
}
